import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { PlaneTakeoff } from 'lucide-react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Integrations | SaaS Product',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>✈️</text></svg>"
				/>
			</head>

			<body className={`min-h-screen ${inter.className}`}>
				<nav className="w-full px-5 border-b flex flex-row items-center justify-between h-[60px] select-none cursor-not-allowed opacity-40">
					<div className="flex flex-row gap-5 items-center">
						<div className="font-semibold text-md flex flex-row gap-3">
							<PlaneTakeoff /> SaaS Product
						</div>
						<div className="font-text text-sm">Workflows</div>
						<div className="font-text text-sm">Accounts</div>
					</div>
					<div className="flex flex-row gap-5">
						<button className="text-sm">Settings</button>
						<button className="text-sm">Log Out</button>
					</div>
				</nav>
				<div className="flex flex-row">
					<aside className="min-w-[250px] min-h-[calc(100vh_-_60px)] border-r p-5  select-none cursor-not-allowed opacity-40">
						<ul className="flex flex-col gap-5">
							<a>Business</a>
							<a>Sales</a>
							<a className="underline underline-offset-4">Integrations</a>
						</ul>
					</aside>
					{children}
				</div>
			</body>
		</html>
	);
}
